"""init

Revision ID: bef1780cbdeb
Revises: 
Create Date: 2025-05-21 09:48:04.971971

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bef1780cbdeb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ADMIN', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=mysql.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('DEVICE', schema=None) as batch_op:
        batch_op.alter_column('device_id',
               existing_type=mysql.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('manager_id',
               existing_type=mysql.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.drop_constraint('DEVICE_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ADMIN', ['manager_id'], ['admin_id'])

    with op.batch_alter_table('DEVICE_MEASUREMENT', schema=None) as batch_op:
        batch_op.alter_column('measurement_id',
               existing_type=mysql.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('emp_id',
               existing_type=mysql.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('device_id',
               existing_type=mysql.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=True)

    with op.batch_alter_table('EMERGENCY_CONTACT', schema=None) as batch_op:
        batch_op.alter_column('emp_id',
               existing_type=mysql.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('EMPLOYEE', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.String(length=255), nullable=True))
        batch_op.alter_column('emp_id',
               existing_type=mysql.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('EMPLOYEE_ATTENDANCE', schema=None) as batch_op:
        batch_op.alter_column('device_id',
               existing_type=mysql.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('emp_id',
               existing_type=mysql.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('EMPLOYEE_HEALTH', schema=None) as batch_op:
        batch_op.add_column(sa.Column('other_conditions', sa.String(length=255), nullable=False))
        batch_op.alter_column('emp_id',
               existing_type=mysql.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=False)

    with op.batch_alter_table('HEALTH_ANOMALY', schema=None) as batch_op:
        batch_op.alter_column('anomaly_id',
               existing_type=mysql.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('emp_id',
               existing_type=mysql.CHAR(length=10),
               type_=sa.String(length=10),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('action_content',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('TOKEN_BLOCKLIST', schema=None) as batch_op:
        batch_op.drop_index('idx_jti')
        batch_op.create_index(batch_op.f('ix_TOKEN_BLOCKLIST_jti'), ['jti'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('TOKEN_BLOCKLIST', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_TOKEN_BLOCKLIST_jti'))
        batch_op.create_index('idx_jti', ['jti'], unique=False)

    with op.batch_alter_table('HEALTH_ANOMALY', schema=None) as batch_op:
        batch_op.alter_column('action_content',
               existing_type=sa.Text(),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('emp_id',
               existing_type=sa.String(length=10),
               type_=mysql.CHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('anomaly_id',
               existing_type=sa.String(length=10),
               type_=mysql.CHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('EMPLOYEE_HEALTH', schema=None) as batch_op:
        batch_op.alter_column('emp_id',
               existing_type=sa.String(length=10),
               type_=mysql.CHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('other_conditions')

    with op.batch_alter_table('EMPLOYEE_ATTENDANCE', schema=None) as batch_op:
        batch_op.alter_column('emp_id',
               existing_type=sa.String(length=10),
               type_=mysql.CHAR(length=10),
               existing_nullable=False)
        batch_op.alter_column('device_id',
               existing_type=sa.String(length=10),
               type_=mysql.CHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('EMPLOYEE', schema=None) as batch_op:
        batch_op.alter_column('emp_id',
               existing_type=sa.String(length=10),
               type_=mysql.CHAR(length=10),
               existing_nullable=False)
        batch_op.drop_column('password')

    with op.batch_alter_table('EMERGENCY_CONTACT', schema=None) as batch_op:
        batch_op.alter_column('emp_id',
               existing_type=sa.String(length=10),
               type_=mysql.CHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('DEVICE_MEASUREMENT', schema=None) as batch_op:
        batch_op.alter_column('device_id',
               existing_type=sa.String(length=10),
               type_=mysql.CHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('emp_id',
               existing_type=sa.String(length=10),
               type_=mysql.CHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('measurement_id',
               existing_type=sa.String(length=10),
               type_=mysql.CHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('DEVICE', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('DEVICE_ibfk_1', 'EMPLOYEE', ['manager_id'], ['emp_id'])
        batch_op.alter_column('manager_id',
               existing_type=sa.String(length=10),
               type_=mysql.CHAR(length=10),
               existing_nullable=True)
        batch_op.alter_column('device_id',
               existing_type=sa.String(length=10),
               type_=mysql.CHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('ADMIN', schema=None) as batch_op:
        batch_op.alter_column('admin_id',
               existing_type=sa.String(length=10),
               type_=mysql.CHAR(length=10),
               existing_nullable=False)

    # ### end Alembic commands ###
